### ISSUE TITLE
Tracking task for Parth (1st week)

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF#63]
- [x] Create an account at https://wikitech.wikimedia.org/wiki/Main_Page
- [x] Send your username to @physikerwelt and wait to be added to the math instance and wait to be approved use the drmf2016 instance exclusively
- [x] Log in to drmf2016
- [x] Set up a local LaTeXML instance http://formulasearchengine.com/LaTeXML
- [x] Configure the Math extension to use that instance e.g. localhost:8888 cf https://www.mediawiki.org/wiki/Extension:Math/advancedSettings
- [x] Create the index
- [x] Set up the mws search engine
- [x] Set up the basex search engine
- [x] Set up DRMF specific configuration i.e. sty files
- [x] Look into #64

**Comment by plato2000** [comment]
Username: Plato2000

**Comment by physikerwelt** [comment]
@plato2000 approved

**Comment by physikerwelt** [comment]
@plato2000 there is info on how to access the drmf2016 instance on https://github.com/DRMF/DRMF/blob/master/doc/The%20SSH%20Guide.MD
If you see that there is something inaccurate in the file, future students will benefit from improvements you make.

**Comment by plato2000** [comment]
1. It doesn't mention that you have to change the INSTANCENAME in the provided config file to whatever instance name its supposed to be (drmf2016 here)
2. I get `ssh: Could not resolve hostname bastion2.wmflabs.org: Name or service not known`

**Comment by physikerwelt** [comment]
my ssh_config looks like that
```
cat ~/.ssh/config
Host bastion1.eqiad.wmflabs
    Hostname bastion.wmflabs.org
    ProxyCommand none

Host bastion2.eqiad.wmflabs
    Hostname bastion2.wmflabs.org
    ProxyCommand none

Host bastion3.eqiad.wmflabs
    Hostname bastion3.wmflabs.org
    ProxyCommand none

Host *.eqiad.wmflabs
    ProxyCommand ssh -a -W %h:%p bastion1.eqiad.wmflabs

Host *.wmflabs
    User physikerwelt

Host drmf
    HostName drmf.eqiad.wmflabs
    ProxyCommand ssh -a -W %h:%p bastion1.eqiad.wmflabs
    User physikerwelt
    LocalForward 8080 localhost:80
```
Can you compare that with the upstream file

**Comment by plato2000** [comment]
So this allows me to establish a connection, but it still asks for a password (I have uploaded my public SSH keys to both gerrit and MediaWiki).

**Comment by physikerwelt** [comment]
do you have a password for your private key?

**Comment by plato2000** [comment]
No, I left it blank. Leaving the password blank when SSHing doesn't work.

**Comment by physikerwelt** [comment]
did you use ssh-copy-id?

**Comment by physikerwelt** [comment]
ah probably you don't need that

**Comment by plato2000** [comment]
How do I run the indexing if it doesn't know where php is?

**Comment by plato2000** [comment]
Never mind, did `vagrant ssh` and got it

**Comment by plato2000** [comment]
```bash
php CreateMWSHarvest.php ../indexes/ 1000000000 --mwsns="mws:"
The mwscript command must be used in multiwiki setups.

Try: mwscript CreateMWSHarvest.php --wiki=wiki ../indexes/ 1000000000 --mwsns=mws:
```
This is after trying to run the indexing command given in the documentation. What is the name of the wiki?

**Comment by physikerwelt** [comment]
I think the wikiname is **wiki**
You can list all wikis via
```
alldbs
```
There are two other commands that might be useful
```
vagrant@mediawiki-vagrant:~$ which mwscript | xargs cat
#!/usr/bin/env bash
# Shell wrapper for multiwiki/MWScript.php.

# Ensure that the script is run as the www-data user
[[ $(whoami) = www-data ]] || exec sudo -u www-data -n -- "$0" "$@"

exec php5 /var/www/w/MWScript.php "$@"
vagrant@mediawiki-vagrant:~$ which foreachwiki | xargs cat
#!/usr/bin/env bash

# Ensure that the script is run as the www-data user
[[ $(whoami) = www-data ]] || exec sudo -u www-data -- "$0" "$@"

CMD=$1
shift

FAILURES=0
for db in $(alldbs); do
  echo -----------------------------------------------------------------
  echo $db
  echo -----------------------------------------------------------------
  mwscript "$CMD" --wiki=$db "$@" |
  sed -u "s/^/$db:  /"

  if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
      ((FAILURES++))
  fi
done

if [[ $FAILURES -ne 0 ]]; then
    echo "$FAILURES wikis failed." >&2
    exit 1
fi
```
CreateMWSHarvest was not buid to run in multiwiki setups. Have you tried passing the --wiki=wiki parameter directly to CreateMWSHarvest.php?

**Comment by plato2000** [comment]
I tried it your way with the --wiki=wiki, but it still says that the mwscript command must be used. When using the mwscript command, it runs, but says it found 0 results to index.

**Comment by plato2000** [comment]
@physikerwelt Where do the localSettings.php files get read from for the extensions? I need to set `$wgMathLaTeXMLUrl='http://localhost:9999'; ` but I don't want to do it from the renderer or something like that.

**Comment by physikerwelt** [comment]
@plato2000 you can try to put it into the local overwrite file we created

**Comment by plato2000** [comment]
@physikerwelt I couldn't find it anywhere, even with a find command
Also, mws works as long as you search for something in its index.

**Comment by physikerwelt** [comment]
@plato2000 cool that mws works, you should check the box
the file is here
```
vagrant@mediawiki-vagrant:/vagrant/settings.d$ cat zz.php 
<?php
$wgDefaultUserOptions['math'] = 'latexml';
$wgMathDisableTexFilter='always';
 $wgDebugToolbar=true;
#$wgMathFullRestbaseURL= 'https://api.formulasearchengine.com/';
vagrant@mediawiki-vagrant:/vagrant/settings.d$ ^C
```

**Comment by plato2000** [comment]
@physikerwelt Ok, for BaseX, running the maven install and it says `Killed` at random times, halting the install process - what could that be?

**Comment by plato2000** [comment]
Another issue - when the LaTeXML url is changed to the localhost url, search does not work. Rendering is fine, but the search fails with some ErrorException.

```php
Exception encountered, of type "ErrorException"
[a86bdeec2f4bd70731805a1f] /wiki/Special:MathSearch ErrorException from line 143 of /vagrant/mediawiki/includes/libs/XmlTypeCheck.php: Unable to load source data
Backtrace:
#0 [internal function]: SpecialMathSearch::exception_error_handler(integer, string, string, integer, array, array)
#1 /vagrant/mediawiki/includes/libs/XmlTypeCheck.php(143): XMLReader->XML(string, NULL, integer)
#2 /vagrant/mediawiki/includes/libs/XmlTypeCheck.php(93): XmlTypeCheck->validateFromInput(NULL, boolean)
#3 /vagrant/mediawiki/extensions/Math/MathMathML.php(302): XmlTypeCheck->__construct(NULL, NULL, boolean)
#4 /vagrant/mediawiki/extensions/Math/MathLaTeXML.php(117): MathMathML->isValidMathML(NULL)
#5 /vagrant/mediawiki/extensions/Math/MathMathML.php(101): MathLaTeXML->doRender()
#6 /vagrant/mediawiki/extensions/MathSearch/MathQueryObject.php(232): MathMathML->render(boolean)
#7 /vagrant/mediawiki/extensions/MathSearch/MathQueryObject.php(155): MathQueryObject->generateContentQueryString()
#8 /vagrant/mediawiki/extensions/MathSearch/includes/MathSearchTerm.php(106): MathQueryObject->getCQuery()
#9 /vagrant/mediawiki/extensions/MathSearch/includes/special/SpecialMathSearch.php(208): MathSearchTerm->doSearch(MathEngineMws)
#10 /vagrant/mediawiki/extensions/MathSearch/includes/special/SpecialMathSearch.php(189): SpecialMathSearch->performSearch()
#11 /vagrant/mediawiki/includes/htmlform/HTMLForm.php(615): SpecialMathSearch->processInput(array, HTMLForm)
#12 /vagrant/mediawiki/includes/htmlform/HTMLForm.php(512): HTMLForm->trySubmit()
#13 /vagrant/mediawiki/includes/htmlform/HTMLForm.php(527): HTMLForm->tryAuthorizedSubmit()
#14 /vagrant/mediawiki/extensions/MathSearch/includes/special/SpecialMathSearch.php(82): HTMLForm->show()
#15 /vagrant/mediawiki/includes/specialpage/SpecialPage.php(412): SpecialMathSearch->execute(NULL)
#16 /vagrant/mediawiki/includes/specialpage/SpecialPageFactory.php(572): SpecialPage->run(NULL)
#17 /vagrant/mediawiki/includes/MediaWiki.php(282): SpecialPageFactory::executePath(Title, RequestContext)
#18 /vagrant/mediawiki/includes/MediaWiki.php(738): MediaWiki->performRequest()
#19 /vagrant/mediawiki/includes/MediaWiki.php(519): MediaWiki->main()
#20 /vagrant/mediawiki/index.php(43): MediaWiki->run()
#21 /var/www/w/index.php(5): include(string)
#22 {main}
```

**Comment by plato2000** [comment]
For ^ install LaTeXML search plugin

**Comment by physikerwelt** [comment]
@plato2000 the repo name is https://github.com/KWARC/LaTeXML-Plugin-MathWebSearch.git

**Comment by plato2000** [comment]
@physikerwelt For the maven install, I'm very tempted to just write a script to run it over and over again until it no longer gets killed- should I do it?

**Comment by physikerwelt** [comment]
I don't have the feeling that that's a good idea.
Maybe it would be worthwhile to look at
http://stackoverflow.com/questions/7278514/maven-compilation-dies-with-killed

**Comment by plato2000** [comment]
@physikerwelt For the search plugin - now search runs but doesn't return any results with the localhost server.

**Comment by plato2000** [comment]
@physikerwelt I tried using the maxmem thing, copied straight from the example, but it still gets killed with maxmem of 128m

**Comment by physikerwelt** [comment]
@plato2000 that's ok. I think it will work after we have the DRMF specific commands set up.

maybe try something like 1g 128m does not seem much. Do you run the tests?

**Comment by plato2000** [comment]
I didn't run the tests. It compiles with 1g. It needed 448mb apparently (said after finish)

**Comment by physikerwelt** [comment]
Can you add that to the readme of the mathosphere project? Maybe one should recommend 512m

**Comment by physikerwelt** [comment]
This is the latexml confing on the xsede server
Listen 8888
<VirtualHost *:8888>
ServerName localhost
 
PerlOptions +Parent
 
<Perl>
$ENV{PLACK_ENV} = 'production';
$ENV{LATEXMLINPUTS} = '/home/DRMF';
$ENV{PROFILE} = 'math';
</Perl>
 
<Location />
SetHandler perl-script
PerlHandler Plack::Handler::Apache2
PerlSetVar psgi_app /usr/local/bin/ltxpsgi
</Location>
 
ErrorLog /var/log/apache2/latexml.error.log
LogLevel warn
CustomLog /var/log/apache2/latexml.access.log combined
</VirtualHost>

**Comment by physikerwelt** [comment]
I have mounted the content of `/home/DRMF` folder of the  xsede  instance now into the vagrant instance in /semantic-macros using /vagrant/Vagrant-extrafile.rb
So you should now have all the data to finish the last step

**Comment by plato2000** [comment]
The configuration file for LaTeXML was removed, as was the BaseX stuff (there is a different cloned version in the home directory, but it does not have the changes made to pom.xml). I have redone both of these. Which directories should I not use (which get overridden)?

**Comment by plato2000** [comment]
Now that the new LaTeXML server configuration files are set, everything renders but it apparently can't connect to the MWS server while it is configured to use the local LaTeXML server.

**Comment by physikerwelt** [comment]
did you install  https://github.com/KWARC/LaTeXML-Plugin-MathWebSearch.git?

**Comment by plato2000** [comment]
Apparently, not correctly. Will do that.

**Comment by plato2000** [comment]
To install the search plugin, I did `perl Makefile.PL`, `make`, and `sudo make install`. After this did not work, I copied the LaTeXML folder from the lib directory of the search plugin to the LaTeXML directory, and this did not work either.

**Comment by physikerwelt** [comment]
@plato2000 did it work last time with search and latexml from localhost?

**Comment by physikerwelt** [comment]
^^ I wonder that the above did not work, how did you verify that the search plugin works doesn't work. A good test is to use a query variable in the request.

**Comment by plato2000** [comment]
search has never worked from latexml and localhost, but it has always worked with the default latexml server. I do a search for \gamma and it works with the default server but not for the localhost. Is there some configuration that has to be done for the search plugin?

**Comment by physikerwelt** [comment]
I get the impression that the search plugin is installed
```
 curl -d 'format=xhtml&whatsin=math&whatsout=math&pmml&cmml&mathtex&nodefaultresources&preload=LaTeX.pool&preload=article.cls&preload=amsmath.sty&preload=amsthm.sty&preload=amstext.sty&preload=amssymb.sty&preload=eucal.sty&preload=%5Bdvipsnames%5Dxcolor.sty&preload=url.sty&preload=hyperref.sty&preload=%5Bids%5Dlatexml.sty&preload=DLMFmath.sty&preload=mws.sty&linelength=90&pmml&cmml&mathtex&nodefaultresources&stylesheet=MWSquery.xsl&tex=%7B%5Cdisplaystyle%20%7B%5Cdisplaystyle%20%5Csin%20%3Fx%7D%7D' localhost:9999
{"status_code":0,"log":"\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/TeX.pool.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/pdfTeX.pool.ltxml... 0.01 sec) 0.27 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/LaTeX.pool.ltxml... 0.25 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/article.cls.ltxml... 0.03 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amsmath.sty.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amsbsy.sty.ltxml... 0.00 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amstext.sty.ltxml... 0.00 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amsopn.sty.ltxml... 0.01 sec) 0.08 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amsthm.sty.ltxml... 0.01 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amssymb.sty.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/amsfonts.sty.ltxml... 0.00 sec) 0.05 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/eucal.sty.ltxml... 0.00 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/xcolor.sty.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/color.sty.ltxml... 0.01 sec)\n(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/graphics/dvipsnam.def... 0.11 sec) 0.59 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/url.sty.ltxml... 0.00 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/hyperref.sty.ltxml...\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/nameref.sty.ltxml... 0.00 sec) 0.05 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/latexml.sty.ltxml... 0.01 sec)\n(Loading /semantic-macros/DRMF/DLMFmath.sty.ltxml...\n(Loading /semantic-macros/DRMF/DLMFfcns.sty.ltxml...\n(Processing definitions /semantic-macros/DRMF/DLMFfcns.sty... 1.10 sec) 1.12 sec)\n(Loading /semantic-macros/DRMF/DRMFfcns.sty.ltxml...\n(Processing definitions /semantic-macros/DRMF/DRMFfcns.sty... 0.55 sec) 0.58 sec) 1.78 sec)\n(Loading /usr/local/share/perl/5.18.2/LaTeXML/Package/mws.sty.ltxml... 0.03 sec)\n\nltxpsgi (LaTeXML version 0.8.1; revision 75c1a06)\nprocessing started Mon May  9 23:13:28 2016\n\n(Digesting TeX Anonymous String...\n(Processing content Literal String \\ensuremat...\n(Processing content Literal String {\\displays...\n(Processing content Literal String \\begin{doc... 0.00 sec) 0.01 sec) 0.01 sec) 0.01 sec)\n(Building...\n(Loading compiled schema /usr/local/share/perl/5.18.2/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.02 sec). 0.08 sec)\n(Rewriting... 0.00 sec)\n(Math Parsing...1 formulae ...[1]\nMath parsing succeeded:\n   ltx:XMath: 1/1\n   ltx:XMWrap: 1/1\nSymbols assumed as simple identifiers (with # of occurences):\n   'qvar' (1)\nSet MATHPARSER_SPECULATE to speculate on possible notations.\n 0.01 sec)\n(Finalizing... 0.00 sec)\nConversion complete: No obvious problems.\n\n(post-processing...\n(Scan  processing... 0.00 sec)\n(CrossRef  processing... 0.00 sec)\n(MathML::Presentation[w/MathML::Content+TeXMath]  processing... 0.01 sec)\n(XSLT[using MWSquery.xsl]  processing... 0.00 sec) 0.01 sec)REQUESTING MATH\n\nPost-processing complete: No obvious problems\nprocessing finished Mon May  9 23:13:29 2016\nStatus:conversion:0 \n","status":"No obvious problems","result":"<?xml version=\"1.0\"?>\n<mws:query xmlns:mws=\"http://search.mathweb.org/ns\" xmlns:m=\"http://www.w3.org/1998/Math/MathML\" limitmin=\"0\" answsize=\"30\">\n  <mws:expr>\n    <m:apply xml:id=\"p1.1.m1.1.3.cmml\" xref=\"p1.1.m1.1.3\">\n      <m:sin xml:id=\"p1.1.m1.1.1.1.cmml\" xref=\"p1.1.m1.1.1.2\"/>\n      <mws:qvar>x</mws:qvar>\n    </m:apply>\n  </mws:expr>\n</mws:query>\n"}
```
It contains <mws:qvar>x</mws:qvar>, which shows that the plugin is active.

**Comment by plato2000** [comment]
How would I ensure that the file at `/etc/apache2/sites-available/latexml.conf` does not get deleted on every `vagrant reload`? I have set the folder up as a synced folder and added the file on the drmf machine, but it still deletes from both sides.

**Comment by physikerwelt** [comment]
^^That has to be configured via a vagrant role. But that's part of #65
