### ISSUE TITLE
Tracking task for Parth (2nd week)

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF#65]
- [x] Finish remaining task from the [first week](https://github.com/DRMF/DRMF/issues/63)
- [x] Set up remote access from your home computer

## Set up drmf-beta using puppet.
The installation and configuration of the services was a huge effort. Manually doing that takes quite a while and is not really interesting. Therefore there is a special DRMF puppet role that is used to set up our servers https://github.com/DRMF/operations-puppet-drmf
Your task is to extend this role, so that
- [x] The LaTeXML Server will be set up automatically
- [x] mathosphere will be installed automatically
- [x] Tomcat get set up and configured to ensure a discontinued running of the search interface
- [x] LaTeXML and the mathosphere RESTBackend are available from host vm [port forwarding](https://github.com/DRMF/operations-puppet-drmf/blob/master/manifests/roles/drmf.yaml)
- [x] ensure that DRMF/operations-puppet-drmf#5  gets reviewed, tested and merged

**Comment by plato2000** [comment]
@physikerwelt 
1. Can I just modify the .pp files from the drmf2016 server and commit from there to the repo?
2. What's wrong with the provided mathosphere.pp file that already exists?
3. Would I test that this works by just doing `vagrant provision`?
4. Should the indexing of files also be automated?

**Comment by physikerwelt** [comment]
@plato2000 
1. yes, that would work. But I would prefere if you forked that repo and push into your fork and do a pull request thereafter, so that I can review your changes
2. It does not work ;-)
3. Yes, but be careful since it might overwrite files you changed manually
4. Yes, but probably not this week and not using puppet. Client and server need to communicate to trigger updates, so that this does not need to be done manually.

**Comment by plato2000** [comment]
```bash
plato2000@drmf2016:/vagrant/puppet/modules/drmf/manifests$ vagrant reload --provision
==> default: Clearing any previously set forwarded ports...                          
==> default: Attempting graceful shutdown of VM...                                   
==> default: Checking if box 'Wikimedia/trusty64-puppet-lxc' is up to date...        
/srv/vagrant-data/gems/gems/mediawiki-vagrant-0.13.0/lib/mediawiki-vagrant/environment.rb:296:in `initialize': Resource temporarily unavailable - /srv/mediawiki-vagrant/puppet/hieradata/vagrant-managed.yaml (Errno::EAGAIN)  
```
This happened after I just modified my puppet file - the last thing to happen was a crash because of a duplicate declaration of apache2. Then I removed the duplicate and now this happens which seems completely unrelated. The error log does not include the file which I modified.

**Comment by plato2000** [comment]
... and now it works with no changes made...

**Comment by plato2000** [comment]
https://github.com/DRMF/operations-puppet-drmf/pull/5

That should have everything, if you want to check @physikerwelt

**Comment by physikerwelt** [comment]
See my comment on https://github.com/DRMF/operations-puppet-drmf/pull/5 to complete this task-list.
