### ISSUE TITLE
Tracking task for Parth (3rd week)

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF#68]
- [ ] Develop test cases for math search on drmf
- [ ] Test stability for BaseX backend (monitoring)
- [ ] Extend query language to support BOOLEAN operations
Please come to my office to discuss the details.

**Comment by physikerwelt** [comment]
@plato2000: @HowardCohl asked me about your progress yesterday. While I apprechiate that you wrote differential progress reports, I could not tell @HowardCohl where exactly you stand. Can you please update the github issues accordingly.
Please also track major issues of other repositories here in the DRMF/DRMF repo, like we did here https://github.com/DRMF/DRMF/issues/65.

**Comment by plato2000** [comment]
@physikerwelt I will do that in the future, would you like me to add issues here for the tomcat issue with mathosphere?

Also, what is the reason we are using BaseX instead of MWS? It seems that MWS works and is more stable as well.
